MBS-7391: Replace the deprecated print_error by moodle exception
h5p/h5p-moodle-plugin pull request #488
Opened 2023-03-02 12:31 UTC by PM84

Print error is deprecated from moodle 4.1. It should be replaced by threw new moodle exception

2024-03-06 09:30 UTC, PM84 commented
Please take into account to merge this as quick as possible. This is realy an anoying error!

2026-06-28 17:24 UTC, otacke requested changes
@PM84 Thanks for the pull request! I think this should have been handled way earlier. I was just made a community maintainer and I am now tring to catch up with all the open issues and pull requests.

I think your contribution is absolutely fine as, but I wonder if we could improve it while we're on it. I wonder, because I don't have much Moodle experience. So, I just tool a look at https://phpdoc.moodledev.io/4.4/da/d58/deprecated.html to learn about what arguments `print_error` expected and I looked at https://moodledev.io/general/development/policies/codingstyle and https://github.com/moodle/moodle/blob/c87bae8d3979b9e2f131e7d237dd42c2f49d6810/public/lib/classes/exception/moodle_exception.php#L30 for Moodle's Exception arguments.

If I understand things correct, then your contribution may be lacking arguments in some places, and without them, the error code would not resolve to the correct error message.

See my comment in your code for details.

2026-06-28 17:24 UTC, otacke commented on grade.php
> +    throw new \moodle_exception('invalidhvp');
As far as I understand it, the 2nd argument `$module` can be used to specify what part of Moodle threw the exception, and I'd assume in the case of the H5P plugin for Moodle, that would be `mod_hvp`. Would it make sense to add that to the exception invocation? I figure the message that would be generated depends on the module argument. I suppose that e.g. 'invalidcoursemodule' is a reserved identifier for Moodle core, but 'invalidhvp' is likely to need the module argument to resolve the message properly, right?

2026-06-28 17:24 UTC, otacke commented on review.php
> +    throw new \moodle_exception('invalidhvp');
See above.

2026-06-28 17:24 UTC, otacke commented on share.php
> +        throw new \moodle_exception('nohubregistration');
Same question here.

2026-06-28 17:24 UTC, otacke commented on share.php
> +        throw new \moodle_exception('invalidtoken');
And here.

2026-06-28 17:24 UTC, otacke commented on share.php
> +        throw new \moodle_exception('contentnotshared');
And here.

2026-06-28 17:30 UTC, otacke commented
Would ...
- close https://github.com/h5p/moodle-mod_hvp/issues/617
- close https://github.com/h5p/moodle-mod_hvp/issues/591
- close https://github.com/h5p/moodle-mod_hvp/issues/577

2026-07-01 10:29 UTC, icc commented
We accepted the https://github.com/h5p/moodle-mod_hvp/pull/618 instead as it was more up-to-date. Feel free to open a new PR if you feel anything was missed. Thank you.

2026-07-01 10:29 UTC, closed without merging